import Head from 'next/head'
import { Inter } from 'next/font/google'
import LogoGrid from '../../components/logoGrid'
import ToolKit from '../../components/toolKit'
import Hero from '../../components/hero'
import Faq from '../../components/faq'
import Cta from '../../components/cta'
import Features from '../../components/features'
import Animated from '../../components/animated'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <div className={inter.className}>
      <section>
        <Hero/>
      </section>
      <section>
      {/* <LogoGrid/> */}
      <Animated>
        <ToolKit/>
      </Animated>
      </section>
      <section className='py-8 my-4'>
        <Cta/>
      </section>
      <section>
      <Animated>

        <Features/>
      </Animated>
      </section>
      <section>
        <Faq/>
      </section>
    </div>
    </>
  )
}
